AWSTemplateFormatVersion: '2010-09-09'
Description: Setup bucket S3
Resources:
  S3BucketDeploy:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: 
        Fn::Join:
          - '-'
          - - !Ref "AWS::StackName"
            - !Ref "AWS::Region"
            - "codepipeline"
            - !Ref "AWS::AccountId"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
